/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/home/v0/it2s/it2s-asn/asn/cd_dictionary_ts_102_894_2_v1.3.1.asn1"
 */

#ifndef	_CurvatureCalculationMode_H_
#define	_CurvatureCalculationMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CurvatureCalculationMode {
	CurvatureCalculationMode_yawRateUsed	= 0,
	CurvatureCalculationMode_yawRateNotUsed	= 1,
	CurvatureCalculationMode_unavailable	= 2
	/*
	 * Enumeration is extensible
	 */
} e_CurvatureCalculationMode;

/* CurvatureCalculationMode */
typedef long long	 CurvatureCalculationMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CurvatureCalculationMode;
asn_struct_free_f CurvatureCalculationMode_free;
asn_struct_print_f CurvatureCalculationMode_print;
asn_constr_check_f CurvatureCalculationMode_constraint;
ber_type_decoder_f CurvatureCalculationMode_decode_ber;
der_type_encoder_f CurvatureCalculationMode_encode_der;
xer_type_decoder_f CurvatureCalculationMode_decode_xer;
xer_type_encoder_f CurvatureCalculationMode_encode_xer;
jer_type_encoder_f CurvatureCalculationMode_encode_jer;
oer_type_decoder_f CurvatureCalculationMode_decode_oer;
oer_type_encoder_f CurvatureCalculationMode_encode_oer;
per_type_decoder_f CurvatureCalculationMode_decode_uper;
per_type_encoder_f CurvatureCalculationMode_encode_uper;
per_type_decoder_f CurvatureCalculationMode_decode_aper;
per_type_encoder_f CurvatureCalculationMode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CurvatureCalculationMode_H_ */
#include <asn_internal.h>
