/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/home/v0/it2s/it2s-asn/asn/cd_dictionary_ts_102_894_2_v1.3.1.asn1"
 * 	`asn1c -S /home/v0/it2s/it2s-asn/skeletons -D cits-message-craft/src/asn1/denm`
 */

#ifndef	_LanePosition_H_
#define	_LanePosition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LanePosition {
	LanePosition_offTheRoad	= -1,
	LanePosition_hardShoulder	= 0,
	LanePosition_outermostDrivingLane	= 1,
	LanePosition_secondLaneFromOutside	= 2
} e_LanePosition;

/* LanePosition */
typedef long long	 LanePosition_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LanePosition_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LanePosition;
asn_struct_free_f LanePosition_free;
asn_struct_print_f LanePosition_print;
asn_constr_check_f LanePosition_constraint;
ber_type_decoder_f LanePosition_decode_ber;
der_type_encoder_f LanePosition_encode_der;
xer_type_decoder_f LanePosition_decode_xer;
xer_type_encoder_f LanePosition_encode_xer;
jer_type_encoder_f LanePosition_encode_jer;
oer_type_decoder_f LanePosition_decode_oer;
oer_type_encoder_f LanePosition_encode_oer;
per_type_decoder_f LanePosition_decode_uper;
per_type_encoder_f LanePosition_encode_uper;
per_type_decoder_f LanePosition_decode_aper;
per_type_encoder_f LanePosition_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LanePosition_H_ */
#include <asn_internal.h>
