/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_DENM;
extern struct asn_TYPE_descriptor_s asn_DEF_PtActivation;
extern struct asn_TYPE_descriptor_s asn_DEF_AccelerationControl;
extern struct asn_TYPE_descriptor_s asn_DEF_TrafficConditionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AccidentSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadworksSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HumanPresenceOnTheRoadSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_WrongWayDrivingSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_AdhesionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_VisibilitySubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_PrecipitationSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_SlowVehicleSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_StationaryVehicleSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HumanProblemSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyVehicleApproachingSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_DangerousCurveSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_SurfaceConditionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_ObstacleOnTheRoadSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_AnimalOnTheRoadSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_CollisionRiskSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalViolationSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_RescueAndRecoveryWorkInProgressSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_DangerousEndOfQueueSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_DangerousSituationSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleBreakdownSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_PostCrashSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_Curvature;
extern struct asn_TYPE_descriptor_s asn_DEF_CurvatureCalculationMode;
extern struct asn_TYPE_descriptor_s asn_DEF_PerformanceClass;
extern struct asn_TYPE_descriptor_s asn_DEF_DriveDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_EmbarkationStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_LongitudinalAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_LateralAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_ExteriorLights;
extern struct asn_TYPE_descriptor_s asn_DEF_SpecialTransportType;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleLength;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyPriority;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringWheelAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleRole;
extern struct asn_TYPE_descriptor_s asn_DEF_YawRate;
extern struct asn_TYPE_descriptor_s asn_DEF_ProtectedCommunicationZonesRSU;
extern struct asn_TYPE_descriptor_s asn_DEF_CenDsrcTollingZone;
extern struct asn_TYPE_descriptor_s asn_DEF_DigitalMap;
extern struct asn_TYPE_descriptor_s asn_DEF_OpeningDaysHours;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module DENM-PDU-Descriptions in /home/v0/it2s/it2s-asn/asn/denm_en_302_637_3_v1.3.1.asn1 */
	&asn_DEF_DENM,	
	/* From module ITS-Container in /home/v0/it2s/it2s-asn/asn/cd_dictionary_ts_102_894_2_v1.3.1.asn1 */
	&asn_DEF_PtActivation,	
	&asn_DEF_AccelerationControl,	
	&asn_DEF_TrafficConditionSubCauseCode,	
	&asn_DEF_AccidentSubCauseCode,	
	&asn_DEF_RoadworksSubCauseCode,	
	&asn_DEF_HumanPresenceOnTheRoadSubCauseCode,	
	&asn_DEF_WrongWayDrivingSubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_AdhesionSubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_VisibilitySubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_PrecipitationSubCauseCode,	
	&asn_DEF_SlowVehicleSubCauseCode,	
	&asn_DEF_StationaryVehicleSubCauseCode,	
	&asn_DEF_HumanProblemSubCauseCode,	
	&asn_DEF_EmergencyVehicleApproachingSubCauseCode,	
	&asn_DEF_HazardousLocation_DangerousCurveSubCauseCode,	
	&asn_DEF_HazardousLocation_SurfaceConditionSubCauseCode,	
	&asn_DEF_HazardousLocation_ObstacleOnTheRoadSubCauseCode,	
	&asn_DEF_HazardousLocation_AnimalOnTheRoadSubCauseCode,	
	&asn_DEF_CollisionRiskSubCauseCode,	
	&asn_DEF_SignalViolationSubCauseCode,	
	&asn_DEF_RescueAndRecoveryWorkInProgressSubCauseCode,	
	&asn_DEF_DangerousEndOfQueueSubCauseCode,	
	&asn_DEF_DangerousSituationSubCauseCode,	
	&asn_DEF_VehicleBreakdownSubCauseCode,	
	&asn_DEF_PostCrashSubCauseCode,	
	&asn_DEF_Curvature,	
	&asn_DEF_CurvatureCalculationMode,	
	&asn_DEF_PerformanceClass,	
	&asn_DEF_DriveDirection,	
	&asn_DEF_EmbarkationStatus,	
	&asn_DEF_LongitudinalAcceleration,	
	&asn_DEF_LateralAcceleration,	
	&asn_DEF_VerticalAcceleration,	
	&asn_DEF_ExteriorLights,	
	&asn_DEF_SpecialTransportType,	
	&asn_DEF_VehicleLength,	
	&asn_DEF_VehicleWidth,	
	&asn_DEF_EmergencyPriority,	
	&asn_DEF_SteeringWheelAngle,	
	&asn_DEF_VehicleRole,	
	&asn_DEF_YawRate,	
	&asn_DEF_ProtectedCommunicationZonesRSU,	
	&asn_DEF_CenDsrcTollingZone,	
	&asn_DEF_DigitalMap,	
	&asn_DEF_OpeningDaysHours,	
	/* From module ASN1C-UsefulInformationObjectClasses in /home/v0/it2s/it2s-asn/skeletons/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

