/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/home/v0/it2s/it2s-asn/asn/cd_dictionary_ts_102_894_2_v1.3.1.asn1"
 */

#ifndef	_PtActivationType_H_
#define	_PtActivationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PtActivationType {
	PtActivationType_undefinedCodingType	= 0,
	PtActivationType_r09_16CodingType	= 1,
	PtActivationType_vdv_50149CodingType	= 2
} e_PtActivationType;

/* PtActivationType */
typedef long long	 PtActivationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PtActivationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PtActivationType;
asn_struct_free_f PtActivationType_free;
asn_struct_print_f PtActivationType_print;
asn_constr_check_f PtActivationType_constraint;
ber_type_decoder_f PtActivationType_decode_ber;
der_type_encoder_f PtActivationType_encode_der;
xer_type_decoder_f PtActivationType_decode_xer;
xer_type_encoder_f PtActivationType_encode_xer;
jer_type_encoder_f PtActivationType_encode_jer;
oer_type_decoder_f PtActivationType_decode_oer;
oer_type_encoder_f PtActivationType_encode_oer;
per_type_decoder_f PtActivationType_decode_uper;
per_type_encoder_f PtActivationType_encode_uper;
per_type_decoder_f PtActivationType_decode_aper;
per_type_encoder_f PtActivationType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PtActivationType_H_ */
#include <asn_internal.h>
