/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/home/v0/it2s/it2s-asn/asn/cd_dictionary_ts_102_894_2_v1.3.1.asn1"
 */

#ifndef	_SequenceNumber_H_
#define	_SequenceNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceNumber */
typedef long long	 SequenceNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SequenceNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SequenceNumber;
asn_struct_free_f SequenceNumber_free;
asn_struct_print_f SequenceNumber_print;
asn_constr_check_f SequenceNumber_constraint;
ber_type_decoder_f SequenceNumber_decode_ber;
der_type_encoder_f SequenceNumber_encode_der;
xer_type_decoder_f SequenceNumber_decode_xer;
xer_type_encoder_f SequenceNumber_encode_xer;
jer_type_encoder_f SequenceNumber_encode_jer;
oer_type_decoder_f SequenceNumber_decode_oer;
oer_type_encoder_f SequenceNumber_encode_oer;
per_type_decoder_f SequenceNumber_decode_uper;
per_type_encoder_f SequenceNumber_encode_uper;
per_type_decoder_f SequenceNumber_decode_aper;
per_type_encoder_f SequenceNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceNumber_H_ */
#include <asn_internal.h>
