/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/home/v0/it2s/it2s-asn/asn/cpm/cpm_complete.asn1"
 * 	`asn1c -S /home/v0/it2s/it2s-asn/skeletons -D cits-message-craft/src/asn1/cpm`
 */

#ifndef	_FreeSpaceAddendum_H_
#define	_FreeSpaceAddendum_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FreeSpaceConfidence.h"
#include "FreeSpaceArea.h"
#include "ShadowingApplies.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SensorIdList;

/* FreeSpaceAddendum */
typedef struct FreeSpaceAddendum {
	FreeSpaceConfidence_t	 freeSpaceConfidence;
	FreeSpaceArea_t	 freeSpaceArea;
	struct SensorIdList	*sensorIDList;	/* OPTIONAL */
	ShadowingApplies_t	*shadowingApplies;	/* DEFAULT TRUE */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FreeSpaceAddendum_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FreeSpaceAddendum;
extern asn_SEQUENCE_specifics_t asn_SPC_FreeSpaceAddendum_specs_1;
extern asn_TYPE_member_t asn_MBR_FreeSpaceAddendum_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SensorIdList.h"

#endif	/* _FreeSpaceAddendum_H_ */
#include <asn_internal.h>
