/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/home/v0/it2s/it2s-asn/asn/cpm/cpm_complete.asn1"
 * 	`asn1c -S /home/v0/it2s/it2s-asn/skeletons -D cits-message-craft/src/asn1/cpm`
 */

#ifndef	_ObjectClass_H_
#define	_ObjectClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ClassConfidence.h"
#include "VehicleSubclass.h"
#include "PersonSubclass.h"
#include "AnimalSubclass.h"
#include "OtherSubclass.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum class_PR {
	class_PR_NOTHING,	/* No components present */
	class_PR_vehicle,
	class_PR_person,
	class_PR_animal,
	class_PR_other
} class_PR;

/* ObjectClass */
typedef struct ObjectClass {
	ClassConfidence_t	 confidence;
	struct Class {
		class_PR present;
		union ObjectClass__class_u {
			VehicleSubclass_t	 vehicle;
			PersonSubclass_t	 person;
			AnimalSubclass_t	 animal;
			OtherSubclass_t	 other;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} Class;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ObjectClass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectClass;
extern asn_SEQUENCE_specifics_t asn_SPC_ObjectClass_specs_1;
extern asn_TYPE_member_t asn_MBR_ObjectClass_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectClass_H_ */
#include <asn_internal.h>
