/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_CPM;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module CPM-PDU-Descriptions in /home/v0/it2s/it2s-asn/asn/cpm/cpm_complete.asn1 */
	&asn_DEF_CPM,	
	/* From module ASN1C-UsefulInformationObjectClasses in /home/v0/it2s/it2s-asn/skeletons/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

