/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/home/v0/it2s/it2s-asn/asn/cd_dictionary_ts_102_894_2_v1.3.1.asn1"
 * 	`asn1c -S /home/v0/it2s/it2s-asn/skeletons -D cits-message-craft/src/asn1/cam`
 */

#include "EmbarkationStatus.h"

/*
 * This type is implemented using BOOLEAN,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_EmbarkationStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (1 << 2))
};
asn_TYPE_descriptor_t asn_DEF_EmbarkationStatus = {
	"EmbarkationStatus",
	"EmbarkationStatus",
	&asn_OP_BOOLEAN,
	asn_DEF_EmbarkationStatus_tags_1,
	sizeof(asn_DEF_EmbarkationStatus_tags_1)
		/sizeof(asn_DEF_EmbarkationStatus_tags_1[0]), /* 1 */
	asn_DEF_EmbarkationStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_EmbarkationStatus_tags_1)
		/sizeof(asn_DEF_EmbarkationStatus_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		BOOLEAN_constraint
	},
	0, 0,	/* No members */
	0	/* No specifics */
};

