/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_CAM;
extern struct asn_TYPE_descriptor_s asn_DEF_TrafficConditionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AccidentSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HumanPresenceOnTheRoadSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_WrongWayDrivingSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_AdhesionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_VisibilitySubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_PrecipitationSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_SlowVehicleSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_StationaryVehicleSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HumanProblemSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyVehicleApproachingSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_DangerousCurveSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_SurfaceConditionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_ObstacleOnTheRoadSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_AnimalOnTheRoadSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_CollisionRiskSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalViolationSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_RescueAndRecoveryWorkInProgressSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_DangerousEndOfQueueSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_DangerousSituationSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleBreakdownSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_PostCrashSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleMass;
extern struct asn_TYPE_descriptor_s asn_DEF_DangerousGoodsExtended;
extern struct asn_TYPE_descriptor_s asn_DEF_HeightLonCarr;
extern struct asn_TYPE_descriptor_s asn_DEF_PosLonCarr;
extern struct asn_TYPE_descriptor_s asn_DEF_PosCentMass;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestResponseIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_StationarySince;
extern struct asn_TYPE_descriptor_s asn_DEF_Temperature;
extern struct asn_TYPE_descriptor_s asn_DEF_WheelBaseVehicle;
extern struct asn_TYPE_descriptor_s asn_DEF_TurningRadius;
extern struct asn_TYPE_descriptor_s asn_DEF_PosFrontAx;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOfOccupants;
extern struct asn_TYPE_descriptor_s asn_DEF_PositioningSolutionType;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleIdentification;
extern struct asn_TYPE_descriptor_s asn_DEF_EnergyStorageType;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadType;
extern struct asn_TYPE_descriptor_s asn_DEF_RelevanceDistance;
extern struct asn_TYPE_descriptor_s asn_DEF_RelevanceTrafficDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_TransmissionInterval;
extern struct asn_TYPE_descriptor_s asn_DEF_ValidityDuration;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionID;
extern struct asn_TYPE_descriptor_s asn_DEF_ItineraryPath;
extern struct asn_TYPE_descriptor_s asn_DEF_Traces;
extern struct asn_TYPE_descriptor_s asn_DEF_NumberOfOccupants;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOfPillars;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictedTypes;
extern struct asn_TYPE_descriptor_s asn_DEF_EventHistory;
extern struct asn_TYPE_descriptor_s asn_DEF_DigitalMap;
extern struct asn_TYPE_descriptor_s asn_DEF_OpeningDaysHours;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module CAM-PDU-Descriptions in /home/v0/it2s/it2s-asn/asn/cam_en_302_637_2_v1.4.1.asn1 */
	&asn_DEF_CAM,	
	/* From module ITS-Container in /home/v0/it2s/it2s-asn/asn/cd_dictionary_ts_102_894_2_v1.3.1.asn1 */
	&asn_DEF_TrafficConditionSubCauseCode,	
	&asn_DEF_AccidentSubCauseCode,	
	&asn_DEF_HumanPresenceOnTheRoadSubCauseCode,	
	&asn_DEF_WrongWayDrivingSubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_AdhesionSubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_VisibilitySubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_PrecipitationSubCauseCode,	
	&asn_DEF_SlowVehicleSubCauseCode,	
	&asn_DEF_StationaryVehicleSubCauseCode,	
	&asn_DEF_HumanProblemSubCauseCode,	
	&asn_DEF_EmergencyVehicleApproachingSubCauseCode,	
	&asn_DEF_HazardousLocation_DangerousCurveSubCauseCode,	
	&asn_DEF_HazardousLocation_SurfaceConditionSubCauseCode,	
	&asn_DEF_HazardousLocation_ObstacleOnTheRoadSubCauseCode,	
	&asn_DEF_HazardousLocation_AnimalOnTheRoadSubCauseCode,	
	&asn_DEF_CollisionRiskSubCauseCode,	
	&asn_DEF_SignalViolationSubCauseCode,	
	&asn_DEF_RescueAndRecoveryWorkInProgressSubCauseCode,	
	&asn_DEF_DangerousEndOfQueueSubCauseCode,	
	&asn_DEF_DangerousSituationSubCauseCode,	
	&asn_DEF_VehicleBreakdownSubCauseCode,	
	&asn_DEF_PostCrashSubCauseCode,	
	&asn_DEF_VehicleMass,	
	&asn_DEF_DangerousGoodsExtended,	
	&asn_DEF_HeightLonCarr,	
	&asn_DEF_PosLonCarr,	
	&asn_DEF_PosCentMass,	
	&asn_DEF_RequestResponseIndication,	
	&asn_DEF_StationarySince,	
	&asn_DEF_Temperature,	
	&asn_DEF_WheelBaseVehicle,	
	&asn_DEF_TurningRadius,	
	&asn_DEF_PosFrontAx,	
	&asn_DEF_PositionOfOccupants,	
	&asn_DEF_PositioningSolutionType,	
	&asn_DEF_VehicleIdentification,	
	&asn_DEF_EnergyStorageType,	
	&asn_DEF_RoadType,	
	&asn_DEF_RelevanceDistance,	
	&asn_DEF_RelevanceTrafficDirection,	
	&asn_DEF_TransmissionInterval,	
	&asn_DEF_ValidityDuration,	
	&asn_DEF_ActionID,	
	&asn_DEF_ItineraryPath,	
	&asn_DEF_Traces,	
	&asn_DEF_NumberOfOccupants,	
	&asn_DEF_PositionOfPillars,	
	&asn_DEF_RestrictedTypes,	
	&asn_DEF_EventHistory,	
	&asn_DEF_DigitalMap,	
	&asn_DEF_OpeningDaysHours,	
	/* From module ASN1C-UsefulInformationObjectClasses in /home/v0/it2s/it2s-asn/skeletons/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

